{{- if and .Values.grafana.enabled .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.grafana.ingress.className }}
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.grafana.ingress.host }}
    secretName: {{ .Values.grafana.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.grafana.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.grafana.name }}
            port:
              number: {{ .Values.grafana.ports.http }}
{{- end }}
