{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.name }}-storage
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.storage.storageClassName }}
  storageClassName: {{ .Values.grafana.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
{{- end }}
