{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.grafana.ports.http }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
{{- end }}
