{{- if .Values.otelCollector.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: otlp-grpc
    port: {{ .Values.otelCollector.ports.grpc }}
    targetPort: otlp-grpc
    protocol: TCP
  - name: otlp-http
    port: {{ .Values.otelCollector.ports.http }}
    targetPort: otlp-http
    protocol: TCP
  - name: metrics
    port: {{ .Values.otelCollector.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
{{- end }}
